apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: {{ .Values.output.name }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "logging-operator-config.labels" . | nindent 4 }}
spec:
  cloudwatch:
    log_group_name: /aws/eks/{{ .Values.target_eks_clustername }}/{{ .Values.namespace }}
    log_stream_name: {{ .Values.output.cloudwatch.log_stream_name }}
    region: {{ .Values.output.cloudwatch.region }}
    auto_create_stream: {{ .Values.output.cloudwatch.auto_create_stream }}
    buffer:
      timekey: {{ .Values.output.cloudwatch.buffer.timekey }}
      timekey_wait: {{ .Values.output.cloudwatch.buffer.timekey_wait }}
      timekey_use_utc: {{ .Values.output.cloudwatch.buffer.timekey_use_utc }}