---
# Source: logging-config/templates/splunk-external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: logging-config-logging-operator-config-splunk-hec-token
  namespace: datajar-django-dev
  labels:
    app.kubernetes.io/name: logging-config
    app.kubernetes.io/instance: logging-operator-config
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/type: datajar
spec:
  refreshInterval: "30m"
  secretStoreRef:
    kind: SecretStore
    name: logging-config-logging-operator-config-secret-manager
  target:
    name: logging-config-logging-operator-config-splunk-hec-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: SplunkHecToken
    remoteRef:
      key: /datajar/dev/portal/secrets
      property: splunk-hec-token
---
# Source: logging-config/templates/flow.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: logging-config-logging-operator-config-flow
  namespace: datajar-django-dev
  labels:
    app.kubernetes.io/name: logging-config
    app.kubernetes.io/instance: logging-operator-config
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/type: datajar
spec:
  filters:
    - tag_normaliser: {}
  match:
    - select:
        labels:
          app.kubernetes.io/type: "datajar"
  localOutputRefs:
    - logging-config-logging-operator-config-cloudwatch-output
    - logging-config-logging-operator-config-splunk-output
---
# Source: logging-config/templates/cloudwatch-output.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: logging-config-logging-operator-config-cloudwatch-output
  namespace: datajar-django-dev
  labels:
    app.kubernetes.io/name: logging-config
    app.kubernetes.io/instance: logging-operator-config
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/type: datajar
spec:
  cloudwatch:
    log_group_name: /aws/eks/euw2-datajar-dev231206/datajar-django-dev
    log_stream_name: ${tag}
    region: eu-west-2
    auto_create_stream: true
    buffer:
      timekey: 30s
      timekey_wait: 30s
      timekey_use_utc: true
---
# Source: logging-config/templates/splunk-output.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: logging-config-logging-operator-config-splunk-output
  namespace: datajar-django-dev
  labels:
    app.kubernetes.io/name: logging-config
    app.kubernetes.io/instance: logging-operator-config
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/type: datajar
spec:
  splunkHec:
    hec_host: https://http-inputs-jamf.splunkcloud.com
    insecure_ssl: true
    hec_port: 443
    hec_token:
      valueFrom:
        secretKeyRef:
          name:  logging-config-logging-operator-config-splunk-hec-token
          key: SplunkHecToken
    index: cloud_dev_datajar_application
    format:
      type: json
---
# Source: logging-config/templates/secret-store.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: logging-config-logging-operator-config-secret-manager
  namespace: datajar-django-dev
  labels:
    app.kubernetes.io/name: logging-config
    app.kubernetes.io/instance: logging-operator-config
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/type: datajar
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
