apiVersion: v2
name: logging-config
description: A Helm chart for configuring logging operator with CloudWatch and Splunk outputs
type: application
version: 0.1.0
appVersion: "1.0"
icon: https://github.com/jamf/insights-logging-operator-config/blob/add-splunk/images/logging-config.png?raw=true
